@startuml

skinparam class {
    ArrowColor black
    BorderColor black
    BackgroundColor white
    NoteBorderColor black
}

package main.java.visitor {

    interface iVisitor {
        Node visitChannel(Channel ctx)
        Node visitSatellite(Satellite ctx)
        Node visitTransponder(Transponder ctx)
        Node visitRoot(Root ctx)
    }
    iVisitor <|-- BaseVistor
}

@enduml
