@startuml

skinparam class {
    ArrowColor black
    BorderColor black
    BackgroundColor white
    NoteBorderColor black
}

package main.java.input {
    class AggregateArgValidator {
        implements IParameterValidator
    }

    class CliArgs {
        -String outputPath
        -String aggregate
        -String outputFormat
        -String inputFormat

        {static} +CliArgs getInstance(String[] argv)
        +Aggregate getAggregate()
        +String getOutputPath()
        +Format getOutputFormat()
        +String getInputPath()
    }

    class FormatArgValidator {
        implements IParameterValidator
    }

    class InputChannel {
        +String sid
        +String name

        {static} +InputChannel(String sid, String name)
    }

    class InputHandler {
        {static} +Node parseJsonToTree(String filename)
        {static} #ArrayList<Node> getSatellitesFromInputFormat(InputTransponder[] inputTransponders) 
    }   

    class InputTransponder {
        +String sat
        +String orbital
        +String pol
        +String freq
        +String sym
        +ArrayList<InputChannel> channels

        {static} +InputTransponder(String sat, String orbital, String pol, String freq, String sym, ArrayList<InputChannel> channels)
    }
}


@enduml
