@startuml

artifact JsonInputFile
artifact UserInput
artifact OutputFile

skinparam component {
    BackgroundColor white
    BorderColor black
    ArrowColor black

}

skinparam interface {
    BackgroundColor white
    BorderColor black
    ArrowColor black
}

skinparam port {
    BorderColor MidnightBlue
    BackgroundColor MidnightBlue
}

skinparam artifact {
    BackgroundColor LightSteelBlue
}

component SatelliteManagement as app{

    port "inputFile" as p_in
    port "CLI Args" as p_args
    port "outputFile" as p_out

    component SatOverTransVisitor #LightGrey
    component Main #LightGrey
    component OutputVisitor #LightGrey
    component JsonParser #LightGrey
    component CLIArgsParser #LightGrey

    interface iVisitor
    interface iOutputVisitor
    interface iFormatParser

    iVisitor -left- SatOverTransVisitor
    Main -left-> iVisitor
    Main -right->iOutputVisitor
    iOutputVisitor -right- OutputVisitor
    Main -up-->iFormatParser
    JsonParser -u- iFormatParser

    () " " as i_in
    i_in -down- JsonParser
    p_in -down-> i_in
    Main -up-> CLIArgsParser
    () " " as i_args
    i_args -down- CLIArgsParser

    Main -up-> i_out
    JsonParser -[hidden]> CLIArgsParser

}


() " " as io_in
io_in -down- p_in
JsonInputFile -right-> io_in

() " " as io_args
io_args -down- p_args
UserInput -right-> io_args
p_args -down-> i_args

() " " as io_out
io_out -down- p_out
OutputFile -right-> io_out
p_out -down-> i_out



@enduml
